baseURL: "https://hugo-startup-1.netlify.app"
languageCode: "en-bg"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 6

taxonomies:
  categories: 'categories'
permalinks:
  categories: "/:slug"
  blog: "/:slug/"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github-dark
    tabWidth: 2
      
defaultContentLanguage: "en"

imaging:
  quality: 95
  resampleFilter: Lanczos

languages:
  en:
    title: Harmony
    description: A global platform for contextual data harmonisation
    copyright: Copyright © 2023 Ulster University.
    languageName: En
    contentDir: content/en
    weight: 1
    menu:
      navbar:
      - name: Home
        weight: 10
        url: /
      - name: News
        weight: 20
        url: /blog/
      - name: Videos
        weight: 30
        url: /videos/
      - name: FAQ
        weight: 50
        url: /frequently-asked-questions/
      - name: About
        weight: 60
      - name: Contact
        url: /contact/
        parent: About
        weight: 10
      - name: Team
        url: /our-team/
        parent: About
        weight: 20
      - name: Tools
        url: /app/
        parent: About
        weight: 30
      - name: Fair data
        url: /fair-data/
        parent: About
        weight: 40
      - name: Projects & Partners
        url: /projects-partners/
        parent: About
        weight: 50
  pt:
    title: Harmony
    description: A global platform for contextual data harmonisation
    copyright: Copyright © 2023 Ulster University.
    languageName: Pt
    contentDir: content/pt
    weight: 2
    menu:
      navbar:
      - name: Início
        weight: 10
        url: /
      - name: Notícias
        weight: 20
        url: '/blog/'
      - name: Videos
        weight: 30
        url: /videos/
      - name: Perguntas Frequentes
        weight: 50
        url: /frequently-asked-questions/
      - name: About
        weight: 60
      - name: Contato
        url: /contact/
        parent: About
        weight: 10
      - name: Equipe
        url: /our-team/
        parent: About
        weight: 20
      - name: Ferramenta
        url: 'https://harmonydata.ac.uk/app/'
        parent: About
        weight: 30
      - name: Princípios FAIR
        url: /fair-data/
        parent: About
        weight: 40
      - name: Projetos & Parceiros
        url: /projects-partners/
        parent: About
        weight: 50

params:
  logo: "/images/logo.svg"
  logo_light: "/images/logo-light.svg"
  author: "Startup"
  github: "#"
  ogimage: "/images/og.png"
  sitename: "Startup"
  twitter: "#"
  analytics_fantom:
  analytics_google: 
      
  navbar:
    sticky: true
    mode: dark
    
  footer:
    layout: footer-2
    mode: dark
