baseURL: "https://harmonydata.ac.uk"
languageCode: "en-bg"

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 6

taxonomies:
  categories: 'categories'
permalinks:
  categories: "/:slug"
  blog: "/:slug/"

outputFormats:
  search:
    baseName: search
    isPlainText: true
    mediaType: application/json
outputs:
  home:
    - HTML
    - RSS
    - search

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github-dark
    tabWidth: 2
      
defaultContentLanguage: "en"

imaging:
  quality: 85
  resampleFilter: Lanczos

languages:
  en:
    title: Harmony
    description: A global platform for contextual data harmonisation
    copyright: Copyright © 2023 Ulster University.
    footer_text: Harmony is a tool for retrospective harmonisation of questionnaire data.
    languageName: En
    contentDir: content/en
    languageCode: en-GB
    weight: 1
    menu:
      navbar:
      - name: News
        weight: 20
        url: /blog/
      - name: Community
        weight: 40
        url: /community
      - name: Case studies
        weight: 45
      - name: Australian Data Archive
        url: /ada/
        parent: Case studies
        weight: 10
      - name: Help
        weight: 50
      - name: FAQ
        parent: Help
        weight: 10
        url: /frequently-asked-questions/
      - name: User guide
        parent: Help
        weight: 20
        url: /formatting-help/
      - name: Developer guide
        parent: Help
        weight: 30
        url: /developer-guide/
      - name: Issue tracker
        parent: Help
        weight: 50
        url: /tracker/
      - name: Videos
        parent: Help
        weight: 60
        url: /videos/
      - name: About
        weight: 60
      - name: Contact
        url: /contact/
        parent: About
        weight: 10
      - name: Team
        url: /our-team/
        parent: About
        weight: 20
      - name: Tools
        url: /app/
        parent: About
        weight: 30
      - name: Fair data
        url: /fair-data/
        parent: About
        weight: 40
      - name: Projects & Partners
        url: /projects-partners/
        parent: About
        weight: 50

      navbar_cta:
      - name: Try Harmony
        url: "/app/"
        pre: outline

      social:
      - name: Facebook
        url: https://www.facebook.com/people/Harmony-Project/100086772661697/
        pre: facebook
        weight: 10
      - name: Instagram
        url: https://www.instagram.com/harmonydata/
        pre: instagram
        weight: 20
      - name: Twitter
        url: https://twitter.com/harmony_data
        pre: twitter
        weight: 30
      - name: YouTube
        url: https://www.youtube.com/channel/UCraLlfBr0jXwap41oQ763OQ
        pre: youtube
        weight: 40
      - name: Linkedin
        url: https://www.linkedin.com/company/harmonydata/about/?viewAsMember=true
        pre: linkedin
        weight: 50
      - name: Github
        url: https://github.com/harmonydata/harmony
        pre: github
        weight: 60
      - name: Discord
        url: https://discord.com/invite/harmonydata
        pre: discord
        weight: 70
        
      footer:
      - name: About us
        weight: 20    
      - name: Our team
        url: "/our-team/"
        parent: About us
        weight: 10
      - name: Contact
        url: "/contact/"
        parent: About us
        weight: 20

      - name: Resources
        weight: 30    
      - name: Blog
        url: "/blog/"
        parent: Resources
        weight: 10
      - name: Videos
        url: "/videos/"
        parent: Resources
        weight: 20
      - name: FAQ
        url: "/frequently-asked-questions/"
        parent: Resources
        weight: 30

      - name: Free AI Tool for Item-Wise Harmonisation
        url: "/item-harmonisation/harmony-a-free-ai-tool-for-item-wise-harmonisation"
        parent: Tools
        weight: 50


      - name: Useful links
        weight: 40    
      - name: Fair data
        url: /fair-data/
        parent: Useful links
        weight: 10
      - name: Projects & partners
        url: /projects-partners/
        parent: Useful links
        weight: 20
      - name: Beck Depression Inventory-II
        url: "/harmonisation-validation/beck-depression-inventory-ii-bdi-ii"
        parent: Useful links
        weight: 40
      - name: GAD-7 vs PHQ-9
        url: "/gad-7-vs-phq-9"
        parent: Useful links
        weight: 60

      - name: Tools
        weight: 50
      - name: Harmony
        url: "/app/"
        parent: Tools
        weight: 10


  pt:
    title: Harmony
    description: Uma plataforma global para harmonização de dados contextuais
    copyright: Copyright © 2023 Ulster University.
    languageName: Pt
    contentDir: content/pt
    languageCode: pt-BR
    weight: 2
    menu:
      navbar:
      - name: Noticias
        weight: 20
        url: '/blog/'
      - name: Videos
        weight: 30
        url: /videos/
      - name: Perguntas
        weight: 50
        url: /frequently-asked-questions/
      - name: Sobre nós
        weight: 60
      - name: Contato
        url: /contact/
        parent: Sobre nós
        weight: 10
      - name: Equipe
        url: /our-team/
        parent: Sobre nós
        weight: 20
      - name: Ferramenta
        url: 'https://harmonydata.ac.uk/app/'
        parent: Sobre nós
        weight: 30
      - name: Principios FAIR
        url: /fair-data/
        parent: Sobre nós
        weight: 40
      - name: Projetos & Parceiros
        url: /projects-partners/
        parent: Sobre nós
        weight: 50

      navbar_cta:
      - name: Use o Harmony
        url: "/app/"
        pre: outline

      social:
      - name: Facebook
        url: https://www.facebook.com/people/Harmony-Project/100086772661697/
        pre: facebook
        weight: 10
      - name: Instagram
        url: https://www.instagram.com/harmonydata/
        pre: instagram
        weight: 20
      - name: Twitter
        url: https://twitter.com/harmony_data
        pre: twitter
        weight: 30
      - name: YouTube
        url: https://www.youtube.com/channel/UCraLlfBr0jXwap41oQ763OQ
        pre: youtube
        weight: 40
      - name: Linkedin
        url: https://www.linkedin.com/company/harmonydata/about/?viewAsMember=true
        pre: linkedin
        weight: 50
      - name: Github
        url: https://github.com/harmonydata/harmony
        pre: github
        weight: 60
      - name: Discord
        url: https://discord.com/invite/harmonydata
        pre: discord
        weight: 70

      footer:
      - name: About us
        weight: 20    
      - name: Our team
        url: "/our-team/"
        parent: About us
        weight: 10
      - name: Contact
        url: "/contact/"
        parent: About us
        weight: 20

      - name: Resources
        weight: 30    
      - name: Blog
        url: "/blog/"
        parent: Resources
        weight: 10
      - name: Videos
        url: "/videos/"
        parent: Resources
        weight: 20
      - name: FAQ
        url: "/frequently-asked-questions/"
        parent: Resources
        weight: 30
        
      - name: Useful links
        weight: 40    
      - name: Fair data
        url: /fair-data/
        parent: Useful links
        weight: 10
      - name: Projects & partners
        url: /projects-partners/
        parent: Useful links
        weight: 20

      - name: Tools
        weight: 50
      - name: Harmony
        url: "/app/"
        parent: Tools
        weight: 10
        

params:
  logo: "/images/logo.svg"
  logo_light: "/images/logo-light.svg"
  author: "Startup"
  github: "#"
  ogimage: "/images/og.png"
  sitename: "Startup"
  twitter: "#"
  analytics_fantom:
  analytics_google: G-S79J6E39ZP
      
  navbar:
    sticky: true
    mode: dark
    
  footer:
    layout: footer-2
    mode: dark

  newsletter:
    mailchimp: 
      action: https://harmonydata.us21.list-manage.com/subscribe/post?u=6c600b2de0b9678055c62637f&amp;id=32eadfb37e&amp;v_id=248&amp;f_id=00b2ece6f0    
