baseURL = 'https://harmonydata.ac.uk/'
languageCode = 'en-gb'
title = 'The Harmony project'

defaultContentLanguage = "en"

[imaging]
quality = 95
resampleFilter = "Lanczos"

[languages.en]
title = "Harmony"
description = "A global platform for contextual data harmonisation"
copyright = "Copyright © 2023 Ulster University."
languageName = "En"
contentDir = "content/en"
weight = 1

[[languages.en.menu.main]]
name = "Home"
weight = 10
url = "/"
[[languages.en.menu.main]]
name = "News"
weight = 20
url = "/blog/"
[[languages.en.menu.main]]
name = "Videos"
weight = 30
url = "/videos/"
[[languages.en.menu.main]]
name = "FAQ"
weight = 50
url = "/frequently-asked-questions/"
[[languages.en.menu.main]]
name = "About"
weight = 60
[[languages.en.menu.main]]
name = "Contact"
url = "/contact/"
parent = "About"
weight = 10
[[languages.en.menu.main]]
name = "Team"
url = "/our-team/"
parent = "About"
weight = 20
[[languages.en.menu.main]]
name = "Tools"
url = "/app/"
parent = "About"
weight = 30
[[languages.en.menu.main]]
name = "Fair data"
url = "/fair-data/"
parent = "About"
weight = 40
[[languages.en.menu.main]]
name = "Projects & Partners"
url = "/projects-partners/"
parent = "About"
weight = 50

[languages.pt]
title = "Harmony"
description = "A global platform for contextual data harmonisation"
copyright = "Copyright © 2023 Ulster University."
languageName = "Pt"
contentDir = "content/pt"
weight = 2

[[languages.pt.menu.main]]
name = "Início"
weight = 10
url = "/"
[[languages.pt.menu.main]]
name = "Notícias"
weight = 20
url = "https://harmonydata.ac.uk/blog/"
[[languages.pt.menu.main]]
name = "Videos"
weight = 30
url = "/videos/"
[[languages.pt.menu.main]]
name = "Perguntas Frequentes"
weight = 50
url = "/frequently-asked-questions/"
[[languages.pt.menu.main]]
name = "About"
weight = 60
[[languages.pt.menu.main]]
name = "Contato"
url = "/contact/"
parent = "About"
weight = 10
[[languages.pt.menu.main]]
name = "Equipe"
url = "/our-team/"
parent = "About"
weight = 20
[[languages.pt.menu.main]]
name = "Ferramenta"
url = "https://harmonydata.ac.uk/app/"
parent = "About"
weight = 30
[[languages.pt.menu.main]]
name = "Princípios FAIR"
url = "/fair-data/"
parent = "About"
weight = 40
[[languages.pt.menu.main]]
name = "Projetos & Parceiros"
url = "/projects-partners/"
parent = "About"
weight = 50


